version: '3'
services:
  registry:
    build: .
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_REGION: your_s3_region
      REGISTRY_STORAGE_S3_BUCKET: your_bucket_name
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: inmemory
      REGISTRY_STORAGE_S3_ACCESSKEY: your_aws_s3_user_access_key
      REGISTRY_STORAGE_S3_SECRETKEY: your_aws_s3_user_secrete_key
